#!/usr/bin/env python3
import os
import sys
import subprocess
import tempfile
import json
import random
from datetime import datetime
from github import Github
import google.generativeai as genai

def log(msg):
    print(f"[{datetime.utcnow().isoformat()}] {msg}", flush=True)

# ---------- Configuration from env ----------
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
TARGET_REPOS = os.environ.get("TARGET_REPOS", "").split(",")
LABELS = os.environ.get("LABELS", "bounty").split(",")
DRY_RUN = os.environ.get("DRY_RUN", "false").lower() == "true"

if not TARGET_REPOS or TARGET_REPOS == ['']:
    log("ERROR: TARGET_REPOS not set. Example: TARGET_REPOS='owner/repo1,owner/repo2'")
    sys.exit(1)
if not GITHUB_TOKEN:
    log("ERROR: GITHUB_TOKEN not set")
    sys.exit(1)
if not GEMINI_API_KEY:
    log("ERROR: GEMINI_API_KEY not set")
    sys.exit(1)

log(f"Target repos: {TARGET_REPOS}")
log(f"Labels: {LABELS}")
log(f"Dry run: {DRY_RUN}")

# ---------- GitHub client ----------
g = Github(GITHUB_TOKEN)

# ---------- Find bounty issues ----------
candidates = []
for repo_name in TARGET_REPOS:
    repo_name = repo_name.strip()
    if not repo_name:
        continue
    try:
        repo = g.get_repo(repo_name)
        issues = repo.get_issues(state='open', labels=LABELS)
        for issue in issues:
            if not issue.pull_request:
                candidates.append((repo_name, issue))
                log(f"Found: {repo_name}#{issue.number} - {issue.title}")
    except Exception as e:
        log(f"Error accessing {repo_name}: {e}")

if not candidates:
    log("No bounty issues found. Exiting.")
    sys.exit(0)

# Pick one (oldest)
chosen_repo, chosen_issue = min(candidates, key=lambda x: x[1].created_at)
log(f"Selected: {chosen_repo}#{chosen_issue.number} - {chosen_issue.title}")

if DRY_RUN:
    log("DRY_RUN: stopping here")
    sys.exit(0)

# ---------- Clone repository ----------
with tempfile.TemporaryDirectory() as tmpdir:
    repo_path = os.path.join(tmpdir, "repo")
    clone_url = f"https://{GITHUB_TOKEN}@github.com/{chosen_repo}.git"
    log(f"Cloning {clone_url} into {repo_path}")
    subprocess.run(["git", "clone", clone_url, repo_path], check=True)
    
    # ---------- Build prompt for Gemini ----------
    issue_body = chosen_issue.body or "(no description)"
    prompt = f"""
You are fixing a GitHub issue. Here is the issue:

Title: {chosen_issue.title}
Description:
{issue_body}

The code is cloned at {repo_path}. Please write a fix. Output ONLY the exact shell commands to modify the necessary files, like:

echo "new content" > path/to/file.py
or
sed -i 's/old/new/g' file.py

Do NOT output any explanation, only commands. The commands will be executed directly.
"""
    log("Calling Gemini...")
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(prompt)
    commands = response.text.strip()
    log(f"Gemini response:\n{commands}")
    
    # ---------- Execute commands ----------
    script_file = os.path.join(tmpdir, "fix.sh")
    with open(script_file, "w") as f:
        f.write("#!/bin/bash\nset -e\n")
        f.write(f"cd {repo_path}\n")
        f.write(commands)
        f.write("\n")
    os.chmod(script_file, 0o755)
    result = subprocess.run([script_file], capture_output=True, text=True)
    if result.returncode != 0:
        log(f"Fix script failed:\n{result.stderr}")
        sys.exit(1)
    log("Fix applied successfully")
    
    # ---------- Commit and push ----------
    branch_name = f"bounty-solve-{chosen_issue.number}"
    subprocess.run(["git", "-C", repo_path, "checkout", "-b", branch_name], check=True)
    subprocess.run(["git", "-C", repo_path, "add", "."], check=True)
    subprocess.run(["git", "-C", repo_path, "commit", "-m", f"Fix #{chosen_issue.number}: {chosen_issue.title}\n\nAuto-generated"], check=True)
    subprocess.run(["git", "-C", repo_path, "push", "-u", "origin", branch_name], check=True)
    log("Pushed branch")
    
    # ---------- Create PR using gh (already installed on runner) ----------
    subprocess.run(["gh", "pr", "create",
                    "--repo", chosen_repo,
                    "--title", f"Auto fix: {chosen_issue.title}",
                    "--body", f"Fixes #{chosen_issue.number}\n\nGenerated by Bounty Solver",
                    "--base", "main",
                    "--head", branch_name],
                   check=True, env={**os.environ, "GH_TOKEN": GITHUB_TOKEN})
    log("PR created")

name: Bounty Solver

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  solve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install PyGithub google-generativeai
      - name: Run bounty solver
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_BOUNTY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TARGET_REPOS: "owner/repo1,owner/repo2"   # <-- CHANGE THIS
          LABELS: "bounty"
          DRY_RUN: "false"
        run: python scripts/bounty_solver_v2.py

log("Done")
